### ISSUE TITLE
There's no attribute 'constraints' at object 'Sequential'

### ISSUE THREAD

**Issue by jd0713** [wassname/rl-portfolio-management#1]
Actor network used Sequential() using keras and it goes into DDPG agent.
And at agent.compile(Adam(lr=3e-5), metrics=['mse'])
there says error that 'Sequential' object has no attribute 'constraints'
It seems that I need to set constraints when use Conv2D, but not sure how to do it.

I also went to keras-rl and run ddpg_pendulum.py, but the same error occured

I think there are three possible way to solve it.

Change python version (3.5.0 --> 2.7)
Input constraint into convolutional layer
Change keras version (2.0.8 --> 1.. whatever)

Can you help me to solve this problem?

Thanks.

**Comment by wassname** [comment]
I was using python 3.5 so that's OK. These are the package version [these](https://github.com/wassname/rl-portfolio-management/blob/master/requirements/requirements.txt) so try using the same version of keras-rl. If that doesn't work try "'keras>=1.0.7'" which is required by the keras-rl version I was using. If that still doesn't work let me know and I'll try running on my machine again

**Comment by jd0713** [comment]
After I change my keras version 2.0.8 to 2.0.3, it worked. 

I should better doing some hyperparameter fitting and apply this code to another data set. 

Thanks a lot!

**Comment by wassname** [comment]
Good to know, good luck!
