### ISSUE TITLE
Hello World

### ISSUE THREAD

**Issue by hackintoshrao** [wassname/rl-portfolio-management#4]
Hi, I'm interested in your implementation of the paper. If there's any task pending (It could be even tests), I would love to contribute. Please let me know the state of the project. The paper reported 4 fold returns, what did your tests reveal?

**Comment by wassname** [comment]
Thanks for the interest! I never managed the returns the paper reported, but I know someone who hasn't published who got better results. 

I tried many models and didn't get great results on any so there may be something wrong with my environment or something else. If I spent more time on this project I would try:

- checking the math in my environment
- DPG models like in paper
- Remove dense layer, the papers author revealed that this was not in the paper
- Try RMSProp not adam, since adam is not good for moving targets, I'm not sure if that applied here but it can't hurt to try.

**Comment by hackintoshrao** [comment]
Thank you for the suggestions. Keep us updated on repo in case of any further improvement in results obtained from model. I'll try these suggestions and report back if something works better.
