### ISSUE TITLE
Calculation of transaction Cost

### ISSUE THREAD

**Issue by trazom21** [wassname/rl-portfolio-management#7]
Hi,

Congrats for this excellent job. 

I have a question about the calculation of the transaction cost in your code.

In (eq 16) in the paper of Jiang et al., the transaction cost is calculated based on the changes of portfolio weights (sum of 1 to m, excluding the cash weight). In the code, the dw1 is of shape of m+1 (including cash weight) and the cost is calculated as: 

mu1 = self.cost * (np.abs(dw1 - w1)).sum()

I wonder if this latter calculation would not have an impact by double counting costs for transactions between cash and asset? Should it not ne replaced by :

 mu1 = self.cost * (np.abs(dw1[1:] - w1[1:])).sum() ?

**Comment by wassname** [comment]
Really nice catch! You're right about that. Your logic makes sense, and I we can test it with a unit test too:

```py
env.reset()
env.step(np.array([1,0,0,0]))
state, reward, done, info = env.step(np.array([0,1,0,0])
print(info['cost'], env.sim.cost)
# 0.0050, 0.0025
```
Here I buy 100% cashs, then sell 100% cash. For the selling step the cost was twice the price, so that's double counting.

I'll make that change you suggested, thanks again for spotting that.

**Comment by trazom21** [comment]
glad to be helpful
